### PR TITLE
Add boilit

### PR DESCRIPTION
**Pull request by gennaro-tedesco**
- `boilit` is a little program that creates boilerplate folder and code structures for neovim plugins (see demo below)
- not a neovim plugin per sé, nevertheless I thought it may be useful to people surfing the webpage as additional resource who want to start off writing plugins themselves

I am unsure if this fits the scope of your webpage: if not, feel free to close :)

[asciicast](https://asciinema.org/a/VpggIG2YeksuuryIHFmVATX43)

### CODE REVIEW

**Comment by lucax88x** [comment]
This website is not only for plugins, your "boilerplate" is absolute fine!

**Comment by lucax88x** [comment]
@gennaro-tedesco 

Sorry, I just noticed you used the wrong folder.
Can you do another pr?

**Comment by gennaro-tedesco** [comment]
> @gennaro-tedesco
> 
> Sorry, I just noticed you used the wrong folder.
> Can you do another pr?

Ooops sorry, yes, I will. I also just realised that there is the wrong reference in the `CONTRIBUTION.md` (that is why) - I will correct that too.

**Comment by lucax88x** [comment]
I corrected it like 1 hour ago, you were unlucky :D just pull it

**Comment by gennaro-tedesco** [comment]
Addressing this discussion to https://github.com/lucax88x/nvim-awesome/pull/28 then.

**Pull request merged**
